configName: sam_rh71_ek
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMRH71F20C
projectName: ''
settings:
  PackageFilter: csp;motor_control;x2c;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMRH71_DFP\2.1.98\samrh71c\atdf\ATSAMRH71F20C.atdf
