package:
  format-version: "1.0.0"
  name: "mc_apps_sam_rh71"
  type: "application"
  status: "production"
  required: true
  version: "3.3.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.17.0"